[project]
name = "weixin-windows-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "mcp[cli]>=1.6.0",
    "uiautomation>=2.0.20",
]
